# PagesCMS Configuration
# https://pagescms.org/docs/configuration/

media:
  input: public/images
  output: images

content:
  # Blog Posts Collection
  - name: posts
    label: Blog Posts
    type: collection
    path: src/content/posts
    view:
      primary: title
      fields: [title, type, date]
      sort: [date, title]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      
      - name: date
        label: Date
        type: date
        required: true
      
      - name: type
        label: Post Type
        type: select
        required: true
        options:
          - label: 🤔 Musings
            value: musings
          - label: 🔗 Links
            value: links
          - label: 📹 Videos
            value: videos
          - label: 🎵 Music
            value: music
        default: musings
      
      - name: url
        label: External URL
        type: string
        description: "Required for Links, Videos, and Music"
      
      - name: tags
        label: Tags
        type: string
        list: true
      
      - name: description
        label: Description
        type: text
      
      - name: dive_deeper
        label: Dive Deeper
        type: string
        list: true
      
      - name: related_posts
        label: Related Posts
        type: string
        list: true
      
      - name: published
        label: Published
        type: boolean
        default: true
      
      - name: body
        label: Content
        type: markdown
        required: true

  # Site Settings
  - name: settings
    label: Site Settings
    type: file
    path: src/data/settings.json
    fields:
      - name: site
        label: Site Information
        type: object
        fields:
          - name: title
            label: Site Title
            type: string
          
          - name: description
            label: Site Description
            type: text
          
          - name: url
            label: Site URL
            type: string
          
          - name: author
            label: Author
            type: string
      
      - name: social
        label: Social Links
        type: object
        fields:
          - name: twitter
            label: Twitter Username
            type: string
          
          - name: github
            label: GitHub Username
            type: string
          
          - name: email
            label: Email
            type: string

  # Blogroll
  - name: blogroll
    label: Blogroll
    type: collection
    path: src/data/blogroll
    view:
      primary: title
      fields: [title, url, featured]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      
      - name: url
        label: URL
        type: string
        required: true
      
      - name: description
        label: Description
        type: text
        required: true
      
      - name: tags
        label: Tags
        type: string
        list: true
      
      - name: featured
        label: Featured
        type: boolean
        default: false