# PagesCMS Configuration
# https://pagescms.org/docs/configuration/

media:
  input: public/images
  output: images

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: src/content/posts
    fields:
      - name: title
        label: Title
        type: string
        required: true
      
      - name: date
        label: Date
        type: date
        required: true
      
      - name: type
        label: Post Type
        type: string
        default: musings
      
      - name: url
        label: External URL
        type: string
      
      - name: tags
        label: Tags
        type: string
        list: true
      
      - name: description
        label: Description
        type: text
      
      - name: dive_deeper
        label: Dive Deeper
        type: string
        list: true
      
      - name: related_posts
        label: Related Posts
        type: string
        list: true
      
      - name: published
        label: Published
        type: boolean
        default: true
      
      - name: body
        label: Content
        type: markdown
        required: true