# PagesCMS Configuration
# https://pagescms.org/docs/configuration/

media:
  input: public/images
  output: /images

content:
  # Blog Posts Collection
  - name: posts
    label: Blog Posts
    type: collection
    path: src/content/posts
    view:
      primary: title
      fields: [title, type, date]
      sort: [date, title]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      
      - name: date
        label: Date
        type: date
        required: true
      
      - name: type
        label: Post Type
        type: select
        required: true
        default: quick-thoughts
        options:
          values:
            - value: taught-by-machine
              label: ðŸ¤– Taught by the machine
            - value: quick-thoughts
              label: ðŸ’­ Quick thoughts
            - value: link-dumps
              label: ðŸ” Link dumps
            - value: deep-dives
              label: ðŸ“š Deep dives
            - value: thats-interesting
              label: ðŸŒŸ That's interesting
            - value: practical
              label: ðŸŽ¯ Practical
            - value: reflections
              label: ðŸ§  Reflections
            - value: data-stories
              label: ðŸ“ˆ Data stories
            - value: news-commentary
              label: ðŸ—žï¸ News & commentary
            - value: videos
              label: ðŸ“¹ Videos
            - value: music
              label: ðŸŽµ Music
            - value: photos
              label: ðŸ“¸ Photos
      
      - name: url
        label: External URL
        type: string
        description: "Required for Links, Videos, and Music"
      
      - name: tags
        label: Tags
        type: string
        list: true
      
      - name: description
        label: Description
        type: text
      
      - name: dive_deeper
        label: Dive Deeper
        type: object
        list: true
        fields:
          - name: text
            label: Link Text
            type: string
            required: true
            description: "The text to display for the link"
          - name: url
            label: URL
            type: string
            required: true
            description: "The destination URL"
          - name: description
            label: Description
            type: text
            description: "Optional description of why this link is relevant"
      
      - name: related_posts
        label: Related Posts
        type: string
        list: true
      
      - name: published
        label: Published
        type: boolean
        default: true
      
      - name: body
        label: Content
        type: rich-text
        required: true
        description: "Use markdown shortcuts: **bold**, *italic*, # headings, - lists, > quotes"
        options:
          media: true
          path: public/images
          extensions: [jpg, jpeg, png, gif, webp]

  # Site Settings
  - name: settings
    label: Site Settings
    type: file
    path: src/data/settings.json
    fields:
      - name: site
        label: Site Information
        type: object
        fields:
          - name: title
            label: Site Title
            type: string
          
          - name: description
            label: Site Description
            type: text
          
          - name: url
            label: Site URL
            type: string
          
          - name: author
            label: Author
            type: string
      
      - name: social
        label: Social Links
        type: object
        fields:
          - name: twitter
            label: Twitter Username
            type: string
          
          - name: github
            label: GitHub Username
            type: string
          
          - name: email
            label: Email
            type: string

  # Blogroll
  - name: blogroll
    label: Blogroll
    type: collection
    path: src/data/blogroll
    view:
      primary: title
      fields: [title, url, featured]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      
      - name: url
        label: URL
        type: string
        required: true
      
      - name: description
        label: Description
        type: text
        required: true
      
      - name: tags
        label: Tags
        type: string
        list: true
      
      - name: featured
        label: Featured
        type: boolean
        default: false