name: Optimize Images

on:
  push:
    paths:
      - 'public/images/**'
  workflow_dispatch:

jobs:
  optimize-images:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install FFmpeg
      run: |
        sudo apt update
        sudo apt install -y ffmpeg

    - name: Run image optimization
      run: |
        # Get list of changed image files
        CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep -E '\.(jpg|jpeg|png|webp)$' | grep '^public/images/' || true)
        
        if [ -z "$CHANGED_FILES" ]; then
          echo "No image files to optimize"
          exit 0
        fi
        
        echo "Changed images detected: $CHANGED_FILES"
        
        # Run our optimization script
        npm run optimize-images -- --verbose
        
        echo "✅ Image optimization completed"

    - name: Commit optimized images
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are changes to commit
        if git diff --quiet; then
          echo "No changes to commit"
        else
          # Add all changes
          git add .
          
          git commit -m "🖼️ Auto-optimize images with FFmpeg" \
                     -m "Automatically optimized images using the FFmpeg-based optimization system" \
                     -m "" \
                     -m "Co-authored-by: Image Optimizer <action@github.com>"
          
          # Push changes
          git push
        fi